# src/report.py
from __future__ import annotations

from pathlib import Path
import pandas as pd
import plotly.express as px
from jinja2 import Template


HTML_TEMPLATE = Template("""
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>{{ title }}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 28px; }
    h1 { margin-bottom: 4px; }
    .meta { color: #444; margin-bottom: 18px; }
    .grid { display: grid; grid-template-columns: 1fr 1fr 1fr 1fr; gap: 12px; margin: 14px 0 22px; }
    .card { border: 1px solid #ddd; border-radius: 10px; padding: 12px; }
    .label { font-size: 12px; color: #666; }
    .value { font-size: 18px; font-weight: 700; margin-top: 4px; }
    table { border-collapse: collapse; width: 100%; margin-top: 10px; }
    th, td { border: 1px solid #ddd; padding: 8px; text-align: right; }
    th { background: #f7f7f7; }
    td:first-child, th:first-child { text-align: left; }
    .section { margin-top: 26px; }
    .summary { background: #f9fafb; border: 1px solid #e5e7eb; padding: 12px; border-radius: 10px; }
    .foot { margin-top: 18px; font-size: 12px; color: #666; }
  </style>
</head>
<body>
  <h1>{{ title }}</h1>
  <div class="meta">Trading date used: <b>{{ trading_date }}</b> | Curve label: <b>{{ curve_label }}</b></div>

  <div class="grid">
    <div class="card"><div class="label">Raw date in CSV</div><div class="value">{{ raw_date }}</div></div>
    <div class="card"><div class="label">Actual</div><div class="value">{{ actual }}</div></div>
    <div class="card"><div class="label">Forecast</div><div class="value">{{ forecast }}</div></div>
    <div class="card"><div class="label">Previous</div><div class="value">{{ previous }}</div></div>
  </div>

  <div class="section">
    <h2>Asset reactions</h2>
    {{ plot_div | safe }}
  </div>

  <div class="section">
    <h2>Auto summary</h2>
    <div class="summary">{{ summary | safe }}</div>
  </div>

  <div class="section">
    <h2>Returns table</h2>
    {{ table_html | safe }}
  </div>

  <div class="foot">
    Generated by Macro Event Impact Tracker.
  </div>
</body>
</html>
""")


def format_pct(x: float) -> str:
    if pd.isna(x):
        return "—"
    return f"{x*100:.2f}%"


def make_summary(event_name: str, trading_date: str, curve_label: str, wide: pd.DataFrame) -> str:
    key_map = {
        "SPY": "equities (SPY)",
        "UUP": "USD (UUP)",
        "TLT": "long bonds (TLT)",
        "GLD": "gold (GLD)",
        "USO": "oil (USO)",
    }
    lines = [f"<b>{event_name}</b> on <b>{trading_date}</b> shows a <b>{curve_label}</b> curve proxy reaction."]

    for ticker, label in key_map.items():
        if ticker in wide.index:
            sd = wide.at[ticker, "same_day_return"]
            nd = wide.at[ticker, "next_day_return"]
            direction_sd = "up" if sd > 0 else "down" if sd < 0 else "flat"
            direction_nd = "up" if nd > 0 else "down" if nd < 0 else "flat"
            lines.append(f"{label}: same-day <b>{direction_sd}</b> ({format_pct(sd)}), next-day <b>{direction_nd}</b> ({format_pct(nd)})")
    return "<br>".join(lines)


def build_plot(df_event: pd.DataFrame, show_two_day: bool = True) -> str:
    plot_df = df_event[["ticker", "same_day_return", "next_day_return", "two_day_return"]].copy()
    plot_df = plot_df.melt(id_vars=["ticker"], var_name="window", value_name="return")

    if not show_two_day:
        plot_df = plot_df[plot_df["window"].isin(["same_day_return", "next_day_return"])]

    window_label = {
        "same_day_return": "Same-day",
        "next_day_return": "Next-day",
        "two_day_return": "2-day cumulative",
    }
    plot_df["window"] = plot_df["window"].map(window_label)

    fig = px.bar(
        plot_df,
        x="ticker",
        y="return",
        color="window",
        barmode="group",
        title="Returns by asset",
    )
    fig.update_yaxes(tickformat=".2%")

    # Return a standalone HTML div (no full HTML page)
    return fig.to_html(full_html=False, include_plotlyjs="cdn")


def build_table(df_event: pd.DataFrame) -> str:
    t = df_event[[
        "ticker", "same_day_return", "next_day_return", "two_day_return", "same_day_z", "next_day_z"
    ]].copy()

    t["same_day_return"] = t["same_day_return"].apply(format_pct)
    t["next_day_return"] = t["next_day_return"].apply(format_pct)
    t["two_day_return"] = t["two_day_return"].apply(format_pct)
    t["same_day_z"] = t["same_day_z"].round(2)
    t["next_day_z"] = t["next_day_z"].round(2)

    # Nice HTML table
    return t.to_html(index=False, escape=False)


def generate_event_report(
    impacts: pd.DataFrame,
    events_csv: pd.DataFrame,
    event_name: str,
    trading_date: str,
    out_dir: str = "reports",
) -> Path:
    df_event = impacts[(impacts["event_name"] == event_name) & (impacts["event_date_trading"] == trading_date)].copy()
    if df_event.empty:
        raise ValueError("No data for that event/date selection.")

    curve_label = df_event["curve_label"].dropna().iloc[0] if df_event["curve_label"].notna().any() else "unknown"
    title = f"US_{event_name}_{trading_date}"

    # Event detail lookup uses raw date from impacts
    raw_date = df_event["event_date_raw"].iloc[0]
    raw_date_dt = pd.to_datetime(raw_date)

    match = events_csv[(events_csv["event_name"] == event_name) & (events_csv["date"] == raw_date_dt)]
    if not match.empty:
        row = match.iloc[0]
        actual = "—" if pd.isna(row.get("actual")) else str(row.get("actual"))
        forecast = "—" if pd.isna(row.get("forecast")) else str(row.get("forecast"))
        previous = "—" if pd.isna(row.get("previous")) else str(row.get("previous"))
        raw_date_str = row["date"].date().isoformat()
    else:
        actual = forecast = previous = "—"
        raw_date_str = raw_date

    wide = df_event.set_index("ticker")[["same_day_return", "next_day_return", "two_day_return"]]
    summary = make_summary(event_name, trading_date, curve_label.replace("_", " "), wide)
    plot_div = build_plot(df_event, show_two_day=True)
    table_html = build_table(df_event)

    html = HTML_TEMPLATE.render(
        title=title,
        trading_date=trading_date,
        curve_label=curve_label.replace("_", " "),
        raw_date=raw_date_str,
        actual=actual,
        forecast=forecast,
        previous=previous,
        summary=summary,
        plot_div=plot_div,
        table_html=table_html,
    )

    out_path = Path(out_dir)
    out_path.mkdir(parents=True, exist_ok=True)
    file_path = out_path / f"{title}.html"
    file_path.write_text(html, encoding="utf-8")
    return file_path
